# Generated by Django 5.0.3 on 2024-05-10 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('date_start', models.DateTimeField(verbose_name='Дата публикации')),
                ('date_end', models.DateTimeField(verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('не начатые', 'не начатые'), ('начатые', 'начатые'), ('архивные', 'архивные')], default='не начатые', max_length=255)),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('birth_date', models.DateTimeField(verbose_name='День Рождения')),
                ('phone_number', models.CharField(max_length=17, verbose_name='Номер телефона')),
                ('description', models.TextField(verbose_name='Описание')),
                ('course', models.ManyToManyField(to='cmrtimurapp.course', verbose_name='Курсы')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17, verbose_name='Номер телефона')),
                ('birth_date', models.DateTimeField(verbose_name='День Рождения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('percent', models.IntegerField(default=0, verbose_name='Проценты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cmrtimurapp.teacher', verbose_name='Учитель'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('date', models.DateTimeField(verbose_name='Дата оплаты')),
                ('description', models.TextField(verbose_name='Описание')),
                ('payment_type', models.CharField(choices=[('наличные', 'наличные'), ('безналичные', 'безналичные')], default='наличные', max_length=255)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cmrtimurapp.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cmrtimurapp.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cmrtimurapp.teacher', verbose_name='Учитель')),
            ],
        ),
    ]
